permissions:
  contents: write
  pull-requests: write

name: release-please

on: workflow_dispatch

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: github-actions-playground
          extra-files: |
            [
              {
                "type": "json",
                "path": "public/manifest.json",
                "jsonpath": "$.version"
              }
            ]
