permissions:
  contents: write
  pull-requests: write

name: release-please

on: workflow_dispatch

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          command: release-pr
          config-file: release-please-config.json
